# Generated by Django 4.0.1 on 2022-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
